let array = [1, 2, 3, 'chicken jockey', true, [1, 2, 3]];
console.log(array);
console.log(array[3]);
console.log(array[5][1]);
array[3] = 'Fuck you';
console.log(array);
console.log(array.length);
array.push('new value');
console.log(array);
let text = array.join('urmom');
console.log(text);